DEFAULT_MODEL_CATALOG = [
    {"provider": "OpenAI", "model": "gpt-5", "label": "GPT-5"},
    {"provider": "OpenAI", "model": "gpt-5-mini", "label": "GPT-5 Mini"},
    {"provider": "OpenAI", "model": "gpt-5-nano", "label": "GPT-5 Nano"},
    {"provider": "OpenAI", "model": "gpt-4.1", "label": "GPT-4.1"},
    {"provider": "OpenAI", "model": "gpt-4.1-mini", "label": "GPT-4.1 Mini"},
    {"provider": "OpenAI", "model": "gpt-4o", "label": "GPT-4o"},
    {"provider": "OpenAI", "model": "gpt-4o-mini", "label": "GPT-4o Mini"},
    {"provider": "OpenAI", "model": "o4-mini", "label": "o4-mini"},
    {"provider": "OpenAI", "model": "o3", "label": "o3"},
    {"provider": "Anthropic", "model": "claude-sonnet-4-5", "label": "Claude Sonnet 4.5"},
    {"provider": "Anthropic", "model": "claude-opus-4-1", "label": "Claude Opus 4.1"},
    {"provider": "Anthropic", "model": "claude-opus-4", "label": "Claude Opus 4"},
    {"provider": "Anthropic", "model": "claude-sonnet-4", "label": "Claude Sonnet 4"},
    {"provider": "Anthropic", "model": "claude-3-7-sonnet-latest", "label": "Claude 3.7 Sonnet"},
    {"provider": "Anthropic", "model": "claude-3-5-sonnet-latest", "label": "Claude 3.5 Sonnet"},
    {"provider": "Anthropic", "model": "claude-3-5-haiku-latest", "label": "Claude 3.5 Haiku"},
    {"provider": "Google", "model": "gemini-2.5-pro", "label": "Gemini 2.5 Pro"},
    {"provider": "Google", "model": "gemini-2.5-flash", "label": "Gemini 2.5 Flash"},
    {"provider": "Google", "model": "gemini-2.0-flash", "label": "Gemini 2.0 Flash"},
    {"provider": "Google", "model": "gemini-2.0-flash-lite", "label": "Gemini 2.0 Flash Lite"},
    {"provider": "xAI", "model": "grok-3-beta", "label": "Grok 3"},
    {"provider": "xAI", "model": "grok-2-latest", "label": "Grok 2"},
    {"provider": "DeepSeek", "model": "deepseek-chat", "label": "DeepSeek Chat"},
    {"provider": "DeepSeek", "model": "deepseek-reasoner", "label": "DeepSeek Reasoner"},
    {"provider": "Qwen", "model": "qwen-max", "label": "Qwen Max"},
    {"provider": "Qwen", "model": "qwen-plus", "label": "Qwen Plus"},
    {"provider": "Qwen", "model": "qwen-turbo", "label": "Qwen Turbo"},
    {"provider": "Qwen", "model": "qwen2.5:14b", "label": "Qwen2.5 14B"},
    {"provider": "Qwen", "model": "qwen2.5:7b", "label": "Qwen2.5 7B"},
    {"provider": "Mistral", "model": "mistral-large-latest", "label": "Mistral Large"},
    {"provider": "Mistral", "model": "mistral-medium-latest", "label": "Mistral Medium"},
    {"provider": "Mistral", "model": "mistral-small-latest", "label": "Mistral Small"},
    {"provider": "Mistral", "model": "codestral-latest", "label": "Codestral"},
    {"provider": "Meta", "model": "llama-3.3-70b-instruct", "label": "Llama 3.3 70B Instruct"},
    {"provider": "Meta", "model": "llama-3.1-70b-instruct", "label": "Llama 3.1 70B Instruct"},
    {"provider": "Meta", "model": "llama-3.1-8b-instruct", "label": "Llama 3.1 8B Instruct"},
    {"provider": "Moonshot", "model": "kimi-k2", "label": "Kimi K2"},
    {"provider": "Moonshot", "model": "moonshot-v1-128k", "label": "Moonshot v1 128k"},
    {"provider": "01.AI", "model": "yi-lightning", "label": "Yi Lightning"},
    {"provider": "01.AI", "model": "yi-large", "label": "Yi Large"},
    {"provider": "OpenRouter", "model": "openrouter/auto", "label": "OpenRouter Auto"},
    {"provider": "OpenRouter", "model": "openai/gpt-4o", "label": "OR GPT-4o"},
    {"provider": "OpenRouter", "model": "openai/gpt-5", "label": "OR GPT-5"},
    {"provider": "OpenRouter", "model": "anthropic/claude-3.5-sonnet", "label": "OR Claude 3.5 Sonnet"},
    {"provider": "OpenRouter", "model": "google/gemini-2.5-pro", "label": "OR Gemini 2.5 Pro"},
    {"provider": "Fireworks", "model": "accounts/fireworks/models/llama-v3p1-70b-instruct", "label": "FW Llama 70B"},
    {"provider": "Together", "model": "meta-llama/Llama-3.3-70B-Instruct-Turbo", "label": "Together Llama 70B"},
    {"provider": "Local", "model": "ollama/llama3.1:8b", "label": "Ollama Llama 3.1 8B"},
    {"provider": "Local", "model": "ollama/qwen2.5:14b", "label": "Ollama Qwen2.5 14B"},
    {"provider": "Local", "model": "ollama/deepseek-r1:14b", "label": "Ollama DeepSeek R1 14B"},
]

